---
devices:
  edge1:
    group:
      "Core_Routers":
         type: internal
         local_add: 192.168.255.1
         asn: 100
         peer: 
          "192.168.255.2":
            description: BGP Session to Edge2
          "192.168.255.3":
            description: BGP Session to Edge3
  edge2:
    group:
      "Core_Routers":
         type: internal
         local_add: 192.168.255.2
         asn: 100
         peer: 
          "192.168.255.1":
            description: BGP Session to Edge1
          "192.168.255.3":
            description: BGP Session to Edge3
  edge3:
    group:
      "Core_Routers":
         type: internal
         local_add: 192.168.255.3
         asn: 100
         peer: 
          "192.168.255.1":
            description: BGP Session to Edge1
          "192.168.255.2":
            description: BGP Session to Edge2
