---
devices:
  pe1:
    interface:
      'ge-0/0/3':
        description: L2VPN to CE1
        log_description: L2VPN Instance PE1 - PE4
    l2vpn:
      'CE1_to_CE7':
        vrf_rd: 100:0011
        vrf_rt: 100:1001
        site: CE1
        site_id: 1
        interface: ge-0/0/3
  pe4:
    interface:
      'ge-0/0/4':
        description: L2VPN to CE1
        log_description: L2VPN Instance PE4 - PE1
    l2vpn:
      'CE7_to_CE1':
        vrf_rd: 100:0014
        vrf_rt: 100:1001
        site: CE7
        site_id: 2
        interface: ge-0/0/4

