---
devices:
  pe1:
    interface:
      'ge-0/0/3':
        description: VPLS LINK to CE1
    vpls:
      'vpls_customer_a':
        vrf_rd: 100:0001
        vrf_rt: 100:1001
        template: default-template
        site_range_id: 20
        mac_table_size: 16
        mac_limit: 5
        vpls_site:
           "Customer_a1":
             site_id: 1
             interface: ge-0/0/3
  pe3:
    interface:
      'ge-0/0/3':
        description: VPLS LINK to CE4
    vpls:
      'vpls_customer_a':
        vrf_rd: 100:0003
        vrf_rt: 100:1001
        template: default-template
        site_range_id: 20
        mac_table_size: 16
        mac_limit: 5
        vpls_site:
           "Customer_a1":
             site_id: 2
             interface: ge-0/0/3
  pe4:
    interface:
      'ge-0/0/4':
        description: VPLS LINK to CE7
    vpls:
      'vpls_customer_a':
        vrf_rd: 100:0004
        vrf_rt: 100:1001
        template: default-template
        site_range_id: 20
        mac_table_size: 16
        mac_limit: 5
        vpls_site:
           "Customer_a1":
             site_id: 3
             interface: ge-0/0/4
